### ISSUE TITLE
api call for solarlog

### ISSUE THREAD

**Issue by riodda** [Sineos/Push-SolarLog-Readings-to-Influxdb-via-MQTT#1]
Hi, sorry to bother you, i was having a look to your script for getting the data from solarlog, one thing i've noticed is the the url you post is very different from the api i have
mi api is like
`https://SOLARLOGIP/api?username=USERNAME&password=PASSWORD&function=getMinVars&solarlog=11269&mode=inverter_detailed&Interval=600&format=json`

while 
`https://SOLARLOGIP/getjp`
answers with a web interface and not with jsonpayload.
Cheers !

**Comment by Sineos** [comment]
The flow is using the REST API of the Solar Log. This needs to be done via a HTTP POST request and does not work if you type it into your browser.

E.g.:
```
$ curl -X POST -H "Content-Type: application/json" -d '{"801":{"170":null}}' 192.168.178.15/getjp
{"801":{"170":{"100":"24.02.23 13:53:30","101":0,"102":0,"103":0,"104":676,"105":0,"106":0,"107":0,"108":30702,"109":80523146,"110":746,"111":11767,"112":24411,"113":558327,"114":1339859,"115":78791444,"116":9210}}}
```

This interface is documented in the SL manuals

**Comment by riodda** [comment]
Thanks for the answer and forgive me for the sillly question, this post call is on the solarlog hardware or on the solarlog web api ? I would expect some kind of autentication on the call.

**Comment by Sineos** [comment]
The data is requested directly from your SL hardware. With "solarlog web api" do you refer to the SL cloud data services like this strange "Solar-Log WEB Enerest" portal? If yes, then these two are completely unrelated and I cannot comment on it since I do not use it.

**Comment by riodda** [comment]
Thanks, now i got it ! Much apreciated !
